"""first auto revision

Revision ID: 3e0cd8aa6245
Revises: 076b9d5353ec
Create Date: 2020-07-20 21:30:28.651447

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e0cd8aa6245"
down_revision = "076b9d5353ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ftr",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("end", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ftr")
    # ### end Alembic commands ###
